---

- name: Add decentraland password auth provider python package
  copy:
    src: "{{ matrix_decentraland_passwords_file_src }}"
    dest: "{{ matrix_synapse_ext_path }}/decentraland_password_auth_provider.py"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0440
  when: "use_decentraland_password_provider|bool"

- set_fact:
    matrix_synapse_password_providers_enabled: true

    matrix_synapse_container_extra_arguments: >
      {{ 
        matrix_synapse_container_extra_arguments|default([])
        +
        ["--mount type=bind,src={{ matrix_synapse_ext_path }}/decentraland_password_auth_provider.py,dst={{ matrix_synapse_in_container_python_packages_path }}/decentraland_password_auth_provider.py,ro"]
      }}
  when: "use_decentraland_password_provider|bool"